# Generated by Django 5.0.3 on 2024-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
    ]
